site_name: Technical-Writer-Portfolio
site_url: https://sykis17.github.io/Technical-Writer-Portfolio/
theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.update.date
    - content.update.time
    - content.action.edit
    - content.action.view
    - navigation.tracking
extra_javascript:
    - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search
  - git-revision-date-localized:
        type: datetime
        timezone: UTC
        fallback_to_build_date: true
  #- pdf-export:
   #   combined: true
    # media_type: print

nav:
  - Home: index.md
  - 'Revision History': revision-history.md
  - 'Emergency Procedures':
      - 'Cabin Altitude': qrh-cabin-alt.md
      - 'Emergency Descent': emergency-descent.md
      - 'Landing Checklist': defered-items-LDG.md
  - 'Maneuvers':
      - 'Nose Low Recovery': qrh-nose-low-recovery.md
      - 'Emergency Descent Manouver': qrh-manouvers.md

  - 'Technical Guides':
      - 'Environment Setup': technical-enviroment-setup-guide.md
      - 'Portfolio Logic': portfolio-guide.md
      - 'Electrical System': elec.md
      - 'Testi': test.md

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.sections

extra:
  last_updated: true  # This shows the user when the manual was last changed