site_name: Technical-Writer-Portfolio
site_url: https://sykis17.github.io/Technical-Writer-Portfolio/
theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.update.date
    - content.update.time
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - content.code.copy
    - navigation.tracking
    - navigation.sections
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
    - js/mermaid-init.js
    - https://sykis17.github.io/Technical-Writer-Portfolio/javascripts/config.js
    - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.snippets:
      check_paths: true
      base_path: docs

plugins:
  - search
  - git-revision-date-localized:
        type: datetime
        timezone: UTC
        fallback_to_build_date: true
  #- pdf-export:
   #   combined: true
    # media_type: print

nav:
  - Home: index.md
#  - CV Viewer: cv-page.md
  - 'OM-A':
    - 'NITS Briefing': nits.md
    - 'PIOSEE Briefing': piosee.md
    - 'Manual Requirements': manualr.md
    - 'List of Terms': glossary.md
    - 'Revision Control (LEP)': lep.md
  - 'OM-B':
    - 'Normal Procedures':
        - 'Vnav Approach': vnav.md
    - 'Emergency Procedures':
        - 'Cabin Altitude': qrh-cabin-alt.md
        - 'Emergency Descent': emergency-descent.md
        - 'Landing Checklist': defered-items-LDG.md
    - 'Manouvers':
        - 'Nose Low Recovery': qrh-nose-low-recovery.md
        - 'Emergency Descent Manouver': qrh-manouvers.md
    - 'FCOM 2':
        - '6. Electrical System': elec.md
  - 'OM-C':
    - 'HF Radio Frequencies': hf.md
  - 'OM-D':
    - 'Revision History': revision-history.md
    - 'Technical Guides':
        - 'Environment Setup': technical-enviroment-setup-guide.md
        - 'Portfolio Logic': portfolio-guide.md
        - 'Testi': test.md
    - 'CRM Training':
        - 'Busy Jim Video': busyjim.md
        - 'TOP GUN': TOPGUN.md
    - 'OPS Tools':
      - World Clock: time.md


extra:
  last_updated: true  # This shows the user when the manual was last changed